// This file is generated by scripts/databricks/generateTableTabelSchema.ts.
// Do not edit it manually.

type TableDeklaration = {
  columnName: string;
  dataType: string;
};

type TableSchemaKey = keyof TableSchemas;

type TableColumnNames<T extends TableSchemaKey> =
  TableSchemas[T][number]["columnName"];

type TableSchemas = {
  "8fa17fc4-60ee-4114-a9dc-6ea6295f7ea7": [
    {
      columnName: "id";
      dataType: "string";
    },
    {
      columnName: "title";
      dataType: "string";
    },
    {
      columnName: "content";
      dataType: "string";
    },
    {
      columnName: "created_at";
      dataType: "bigint";
    },
    {
      columnName: "created_by";
      dataType: "string";
    },
    {
      columnName: "is_active";
      dataType: "boolean";
    },
    {
      columnName: "ttl";
      dataType: "int";
    },
  ];
  "active-users-over-time": [
    {
      columnName: "fleet_name";
      dataType: "string";
    },
    {
      columnName: "user_id";
      dataType: "string";
    },
    {
      columnName: "user_last_name";
      dataType: "string";
    },
    {
      columnName: "user_sure_name";
      dataType: "string";
    },
    {
      columnName: "car_id_list";
      dataType: "string";
    },
    {
      columnName: "engine_type";
      dataType: "string";
    },
    {
      columnName: "product_range";
      dataType: "string";
    },
    {
      columnName: "gearbox_type";
      dataType: "string";
    },
    {
      columnName: "vehicle_type";
      dataType: "string";
    },
    {
      columnName: "ecu_name";
      dataType: "string";
    },
    {
      columnName: "variant";
      dataType: "string";
    },
    {
      columnName: "creation_date_start";
      dataType: "timestamp";
    },
    {
      columnName: "creation_date_end";
      dataType: "timestamp";
    },
    {
      columnName: "processing_date_start";
      dataType: "timestamp";
    },
    {
      columnName: "processing_date_end";
      dataType: "timestamp";
    },
    {
      columnName: "fleet_creation_date";
      dataType: "timestamp";
    },
    {
      columnName: "uid";
      dataType: "string";
    },
    {
      columnName: "SA_codes";
      dataType: "string";
    },
  ];
  "cumulative-fleets": [
    {
      columnName: "fleet_name";
      dataType: "string";
    },
    {
      columnName: "user_id";
      dataType: "string";
    },
    {
      columnName: "user_last_name";
      dataType: "string";
    },
    {
      columnName: "user_sure_name";
      dataType: "string";
    },
    {
      columnName: "car_id_list";
      dataType: "string";
    },
    {
      columnName: "engine_type";
      dataType: "string";
    },
    {
      columnName: "product_range";
      dataType: "string";
    },
    {
      columnName: "gearbox_type";
      dataType: "string";
    },
    {
      columnName: "vehicle_type";
      dataType: "string";
    },
    {
      columnName: "ecu_name";
      dataType: "string";
    },
    {
      columnName: "variant";
      dataType: "string";
    },
    {
      columnName: "creation_date_start";
      dataType: "timestamp";
    },
    {
      columnName: "creation_date_end";
      dataType: "timestamp";
    },
    {
      columnName: "processing_date_start";
      dataType: "timestamp";
    },
    {
      columnName: "processing_date_end";
      dataType: "timestamp";
    },
    {
      columnName: "fleet_creation_date";
      dataType: "timestamp";
    },
    {
      columnName: "uid";
      dataType: "string";
    },
    {
      columnName: "SA_codes";
      dataType: "string";
    },
  ];
  "dtc-table": [
    {
      columnName: "dtc_number";
      dataType: "string";
    },
    {
      columnName: "IFileName";
      dataType: "string";
    },
    {
      columnName: "CarName";
      dataType: "string";
    },
    {
      columnName: "ECUName";
      dataType: "string";
    },
    {
      columnName: "SAENumber";
      dataType: "string";
    },
    {
      columnName: "SymptomName";
      dataType: "string";
    },
    {
      columnName: "HWVersion";
      dataType: "string";
    },
    {
      columnName: "HWPartNumber";
      dataType: "string";
    },
    {
      columnName: "ErrorText";
      dataType: "string";
    },
    {
      columnName: "OdometerRead";
      dataType: "int";
    },
    {
      columnName: "MIL";
      dataType: "int";
    },
    {
      columnName: "IsStored";
      dataType: "int";
    },
    {
      columnName: "IsActive";
      dataType: "int";
    },
    {
      columnName: "IsPending";
      dataType: "int";
    },
    {
      columnName: "DTCStatus";
      dataType: "string";
    },
    {
      columnName: "DTCStatusByte";
      dataType: "string";
    },
    {
      columnName: "Status_bit_0";
      dataType: "boolean";
    },
    {
      columnName: "Status_bit_1";
      dataType: "boolean";
    },
    {
      columnName: "Status_bit_2";
      dataType: "boolean";
    },
    {
      columnName: "Status_bit_3";
      dataType: "boolean";
    },
    {
      columnName: "Status_bit_4";
      dataType: "boolean";
    },
    {
      columnName: "Status_bit_5";
      dataType: "boolean";
    },
    {
      columnName: "Status_bit_6";
      dataType: "boolean";
    },
    {
      columnName: "Status_bit_7";
      dataType: "boolean";
    },
    {
      columnName: "TestCompletion";
      dataType: "boolean";
    },
    {
      columnName: "LastUpdate";
      dataType: "timestamp";
    },
    {
      columnName: "ProjectName";
      dataType: "string";
    },
    {
      columnName: "Service_tool_name";
      dataType: "string";
    },
    {
      columnName: "Service_tool_user_ID";
      dataType: "string";
    },
    {
      columnName: "Service_tool_version";
      dataType: "string";
    },
    {
      columnName: "Service_tool_comment";
      dataType: "string";
    },
    {
      columnName: "Odometer_first_occurence";
      dataType: "string";
    },
    {
      columnName: "Odometer_last_occurence";
      dataType: "string";
    },
    {
      columnName: "Occurrence_Flag";
      dataType: "string";
    },
    {
      columnName: "Operation_Cycle_Counter";
      dataType: "string";
    },
    {
      columnName: "External_Tester_Present_Flag";
      dataType: "string";
    },
    {
      columnName: "FrequencyCount";
      dataType: "int";
    },
    {
      columnName: "Failed_Counter";
      dataType: "string";
    },
    {
      columnName: "MotorPrjName";
      dataType: "string";
    },
    {
      columnName: "MotorTypeName";
      dataType: "string";
    },
    {
      columnName: "CarTypeName";
      dataType: "string";
    },
    {
      columnName: "GearboxTypeName";
      dataType: "string";
    },
    {
      columnName: "MotorModelName";
      dataType: "string";
    },
    {
      columnName: "CarSeries";
      dataType: "string";
    },
    {
      columnName: "IFileCreated";
      dataType: "timestamp";
    },
    {
      columnName: "IFileMileage";
      dataType: "int";
    },
    {
      columnName: "DTCCount";
      dataType: "bigint";
    },
    {
      columnName: "IEntryDate";
      dataType: "date";
    },
    {
      columnName: "DataSetName";
      dataType: "string";
    },
    {
      columnName: "IsRedundant";
      dataType: "boolean";
    },
    {
      columnName: "OStatusId";
      dataType: "int";
    },
    {
      columnName: "DateCreated";
      dataType: "string";
    },
    {
      columnName: "Status";
      dataType: "string";
    },
    {
      columnName: "Variant";
      dataType: "string";
    },
    {
      columnName: "V4";
      dataType: "string";
    },
    {
      columnName: "V5";
      dataType: "string";
    },
    {
      columnName: "V6";
      dataType: "string";
    },
    {
      columnName: "V7";
      dataType: "string";
    },
    {
      columnName: "SwVersion";
      dataType: "array<string>";
    },
    {
      columnName: "Footprint";
      dataType: "array<string>";
    },
    {
      columnName: "is_additional_care_enriched";
      dataType: "boolean";
    },
    {
      columnName: "is_care_enriched";
      dataType: "boolean";
    },
    {
      columnName: "SA_codes";
      dataType: "string";
    },
    {
      columnName: "is_legacy_data";
      dataType: "boolean";
    },
    {
      columnName: "fahrzeug_baumuster";
      dataType: "string";
    },
    {
      columnName: "getriebe_baumuster";
      dataType: "string";
    },
    {
      columnName: "motor_baumuster";
      dataType: "string";
    },
    {
      columnName: "DTCDataId";
      dataType: "bigint";
    },
    {
      columnName: "FileId";
      dataType: "bigint";
    },
    {
      columnName: "CarId";
      dataType: "bigint";
    },
    {
      columnName: "OperatorId";
      dataType: "bigint";
    },
  ];
};
