import { watch } from "node:fs";
import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

type TableSchemaColumn = {
  name: string;
  type: string;
};

type TableSchemaFile = {
  tables: Array<{
    columns: TableSchemaColumn[];
  }>;
};

const SCHEMA_DIRECTORY = path.resolve(process.cwd(), "pagesConfig", "schemas");
const OUTPUT_PATH = path.resolve(process.cwd(), "types", "schemas.d.ts");
const WATCH_DEBOUNCE_MS = 100;
const runOnce = process.argv.includes("--once");

generateTypes()
  .then(() => {
    if (!runOnce) {
      watchSchemas();
    }
  })
  .catch((error: unknown) => {
    reportError(error);
    process.exitCode = 1;
  });

async function generateTypes(): Promise<void> {
  const fileNames = (await readdir(SCHEMA_DIRECTORY))
    .filter((fileName) => path.extname(fileName) === ".json")
    .sort();

  const schemas = await Promise.all(
    fileNames.map(async (fileName) => {
      const filePath = path.join(SCHEMA_DIRECTORY, fileName);
      const content = await readFile(filePath, "utf8");
      const parsedSchema: unknown = JSON.parse(content);

      assertTableSchemaFile(parsedSchema, fileName);

      return {
        key: path.basename(fileName, ".json"),
        columns: parsedSchema.tables.flatMap((table) => table.columns),
      };
    }),
  );

  const output = renderTypes(schemas);

  await writeFile(OUTPUT_PATH, output, "utf8");

  console.log(
    `Generated ${path.relative(process.cwd(), OUTPUT_PATH)} from ${schemas.length} schema file(s).`,
  );
}

function assertTableSchemaFile(
  value: unknown,
  fileName: string,
): asserts value is TableSchemaFile {
  if (!isRecord(value) || !Array.isArray(value.tables)) {
    throw new Error(`${fileName}: expected a "tables" array.`);
  }

  for (const [tableIndex, table] of value.tables.entries()) {
    if (!isRecord(table) || !Array.isArray(table.columns)) {
      throw new Error(
        `${fileName}: expected tables[${tableIndex}].columns to be an array.`,
      );
    }

    for (const [columnIndex, column] of table.columns.entries()) {
      if (
        !isRecord(column) ||
        typeof column.name !== "string" ||
        typeof column.type !== "string"
      ) {
        throw new Error(
          `${fileName}: expected tables[${tableIndex}].columns[${columnIndex}] to contain string properties "name" and "type".`,
        );
      }
    }
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function renderTypes(
  schemas: Array<{ key: string; columns: TableSchemaColumn[] }>,
): string {
  const schemaEntries = schemas
    .map(({ key, columns }) => {
      const columnEntries = columns
        .map(
          ({ name, type }) =>
            `    {\n      columnName: ${JSON.stringify(name)};\n      dataType: ${JSON.stringify(type)};\n    },`,
        )
        .join("\n");

      return `  ${JSON.stringify(key)}: [\n${columnEntries}\n  ];`;
    })
    .join("\n");

  return `// This file is generated by scripts/databricks/generateTableTabelSchema.ts.\n// Do not edit it manually.\n\ntype TableDeklaration = {\n  columnName: string;\n  dataType: string;\n};\n\ntype TableSchemaKey = keyof TableSchemas;\n\ntype TableColumnNames<T extends TableSchemaKey> =\n  TableSchemas[T][number]["columnName"];\n\ntype TableSchemas = {\n${schemaEntries}\n};\n`;
}

function watchSchemas(): void {
  let regenerationTimer: NodeJS.Timeout | undefined;

  const watcher = watch(SCHEMA_DIRECTORY, (_eventType, fileName) => {
    if (fileName && path.extname(fileName) !== ".json") {
      return;
    }

    clearTimeout(regenerationTimer);
    regenerationTimer = setTimeout(() => {
      generateTypes().catch(reportError);
    }, WATCH_DEBOUNCE_MS);
  });

  watcher.on("error", reportError);

  console.log(
    `Watching ${path.relative(process.cwd(), SCHEMA_DIRECTORY)} for changes...`,
  );
}

function reportError(error: unknown): void {
  const message = error instanceof Error ? error.message : String(error);

  console.error(`Schema type generation failed: ${message}`);
}
